name: script-test

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_call: ~
  workflow_dispatch: ~

jobs:

  script-test:
    runs-on: ubuntu-latest

    # This permission is required to allow writing comments and reporting check status.
    permissions:
      actions: read
      checks: write
      contents: read
      issues: write
      pull-requests: write
      repository-projects: read
      statuses: write

    steps:
    
      - name: Test
        run: |
          echo "Status: ${{ job.status }} ${{ job.status == 'success' && 'hooray' || '-1' }}"
          echo "${{ secrets.ABC }}" | md5sum

